GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2F0IiwiaWF0IjoxNjUyNjM2MDQwfQ.nicd3COCzuuH_z-8NRkOkU7G0L-zVqMjkXE8-0JAMK0


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "kat"
}